import type { Metadata } from 'next';
import { Inter, Ubuntu, Mali } from 'next/font/google';
import './globals.css';
import React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { NextIntlClientProvider } from 'next-intl';
import { StoreProvider } from '@/store/StoreProvider';
import { Footer } from '@/components/footer';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing, Locale } from '@/i18n/routing';
import { Header } from '@/components/header';

const inter = Inter({
  subsets: ['cyrillic'],
  variable: '--font-inter',
  display: 'swap',
});

const ubuntu = Ubuntu({
  subsets: ['cyrillic'],
  variable: '--font-ubuntu',
  weight: ['400', '700'],
  display: 'swap',
});

const mali = Mali({
  subsets: ['latin'],
  variable: '--font-mali',
  weight: ['700'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Студія завивок',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale || 'uk'} suppressHydrationWarning={true}>
      <body className={`${inter.variable} ${ubuntu.variable} ${mali.variable}`}>
        <StoreProvider>
          <AppRouterCacheProvider>
            <NextIntlClientProvider messages={messages}>
              <Header />
              <main className="relative overflow-x-hidden">{children}</main>
              <Footer />
            </NextIntlClientProvider>
          </AppRouterCacheProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
