import { CurlSize, HairLength } from '@/components/zavivka/types';

export type Photo = {
  src: string;
  hairLength: HairLength;
  curlSize: CurlSize;
  master: string;
  colored: boolean;
  slug: string;
  id: string;
};

export const photos: Photo[] = [
  // Валентина Антоненко начало
  {
    id: '1',
    src: '/images/valentina/valentina-1.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '2',
    src: '/images/valentina/valentina-2.webp',
    hairLength: 'По пояс',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '3',
    src: '/images/valentina/valentina-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '4',
    src: '/images/valentina/valentina-4.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '5',
    src: '/images/valentina/valentina-5.jpg',
    hairLength: 'Короткі',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '6',
    src: '/images/valentina/valentina-6.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '7',
    src: '/images/valentina/valentina-7.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '8',
    src: '/images/valentina/valentina-8.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '9',
    src: '/images/valentina/valentina-9.webp',
    hairLength: 'По пояс',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '10',
    src: '/images/valentina/valentina-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '11',
    src: '/images/valentina/valentina-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '12',
    src: '/images/valentina/valentina-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '13',
    src: '/images/valentina/valentina-13.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '14',
    src: '/images/valentina/valentina-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '15',
    src: '/images/valentina/valentina-15.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  // Валентина Антоненко конец

  // Артем начало
  {
    id: '16',
    src: '/images/artem/artem-1.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '17',
    src: '/images/artem/artem-2.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '18',
    src: '/images/artem/artem-3.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '19',
    src: '/images/artem/artem-4.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '20',
    src: '/images/artem/artem-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '21',
    src: '/images/artem/artem-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '22',
    src: '/images/artem/artem-7.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '23',
    src: '/images/artem/artem-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '24',
    src: '/images/artem/artem-9.webp',
    hairLength: 'По плечі',
    curlSize: 'Інтенсивний',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  // Артем конец

  // Кузьменко начало
  {
    id: '25',
    src: '/images/a-kuzmenko/kuzmenko-1.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '26',
    src: '/images/a-kuzmenko/kuzmenko-2.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '27',
    src: '/images/a-kuzmenko/kuzmenko-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: false,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '28',
    src: '/images/a-kuzmenko/kuzmenko-4.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '29',
    src: '/images/a-kuzmenko/kuzmenko-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '30',
    src: '/images/a-kuzmenko/kuzmenko-6.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '31',
    src: '/images/a-kuzmenko/kuzmenko-7.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '32',
    src: '/images/a-kuzmenko/kuzmenko-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '33',
    src: '/images/a-kuzmenko/kuzmenko-9.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '34',
    src: '/images/a-kuzmenko/kuzmenko-10.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '35',
    src: '/images/a-kuzmenko/kuzmenko-11.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '36',
    src: '/images/a-kuzmenko/kuzmenko-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  // Кузьменко конец

  // vika omelchenko начало
  {
    id: '37',
    src: '/images/vika-omelchenko/vika-omelchenko-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '38',
    src: '/images/vika-omelchenko/vika-omelchenko-2.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '39',
    src: '/images/vika-omelchenko/vika-omelchenko-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '40',
    src: '/images/vika-omelchenko/vika-omelchenko-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '41',
    src: '/images/vika-omelchenko/vika-omelchenko-5.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '42',
    src: '/images/vika-omelchenko/vika-omelchenko-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '43',
    src: '/images/vika-omelchenko/vika-omelchenko-7.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '44',
    src: '/images/vika-omelchenko/vika-omelchenko-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '45',
    src: '/images/vika-omelchenko/vika-omelchenko-9.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '46',
    src: '/images/vika-omelchenko/vika-omelchenko-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '47',
    src: '/images/vika-omelchenko/vika-omelchenko-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '48',
    src: '/images/vika-omelchenko/vika-omelchenko-12.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '49',
    src: '/images/vika-omelchenko/vika-omelchenko-13.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '50',
    src: '/images/vika-omelchenko/vika-omelchenko-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '51',
    src: '/images/vika-omelchenko/vika-omelchenko-15.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '52',
    src: '/images/vika-omelchenko/vika-omelchenko-16.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  // vika omelchenko конец

  // Вікторія Салій начало
  {
    id: '53',
    src: '/images/viktoriya-salyi/viktoriya-salyi-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '54',
    src: '/images/viktoriya-salyi/viktoriya-salyi-2.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '55',
    src: '/images/viktoriya-salyi/viktoriya-salyi-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '56',
    src: '/images/viktoriya-salyi/viktoriya-salyi-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '57',
    src: '/images/viktoriya-salyi/viktoriya-salyi-5.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '58',
    src: '/images/viktoriya-salyi/viktoriya-salyi-6.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '59',
    src: '/images/viktoriya-salyi/viktoriya-salyi-7.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '60',
    src: '/images/viktoriya-salyi/viktoriya-salyi-8.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '61',
    src: '/images/viktoriya-salyi/viktoriya-salyi-9.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '62',
    src: '/images/viktoriya-salyi/viktoriya-salyi-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '63',
    src: '/images/viktoriya-salyi/viktoriya-salyi-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '64',
    src: '/images/viktoriya-salyi/viktoriya-salyi-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '65',
    src: '/images/viktoriya-salyi/viktoriya-salyi-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '66',
    src: '/images/viktoriya-salyi/viktoriya-salyi-14.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '67',
    src: '/images/viktoriya-salyi/viktoriya-salyi-15.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '68',
    src: '/images/viktoriya-salyi/viktoriya-salyi-16.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '69',
    src: '/images/viktoriya-salyi/viktoriya-salyi-17.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '70',
    src: '/images/viktoriya-salyi/viktoriya-salyi-18.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '71',
    src: '/images/viktoriya-salyi/viktoriya-salyi-19.webp',
    hairLength: 'Короткі',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '72',
    src: '/images/viktoriya-salyi/viktoriya-salyi-20.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '73',
    src: '/images/viktoriya-salyi/viktoriya-salyi-21.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '74',
    src: '/images/viktoriya-salyi/viktoriya-salyi-22.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  // Вікторія Салій конец
];
