import { CurlSize, HairLength } from '@/components/zavivka/types';

export type Photo = {
  src: string;
  hairLength: HairLength;
  curlSize: CurlSize;
  master: string;
  colored: boolean;
  slug: string;
  id: string;
};

export const photos: Photo[] = [
  // Валентина Антоненко начало
  {
    id: '1',
    src: '/images/valentina/valentina-1.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '2',
    src: '/images/valentina/valentina-2.webp',
    hairLength: 'По пояс',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '3',
    src: '/images/valentina/valentina-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '4',
    src: '/images/valentina/valentina-4.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '5',
    src: '/images/valentina/valentina-5.jpg',
    hairLength: 'Короткі',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '6',
    src: '/images/valentina/valentina-6.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '7',
    src: '/images/valentina/valentina-7.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '8',
    src: '/images/valentina/valentina-8.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '9',
    src: '/images/valentina/valentina-9.webp',
    hairLength: 'По пояс',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '10',
    src: '/images/valentina/valentina-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '11',
    src: '/images/valentina/valentina-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '12',
    src: '/images/valentina/valentina-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '13',
    src: '/images/valentina/valentina-13.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валентина Антоненко',
    colored: true,
    slug: 'valentina-antonenko',
  },
  {
    id: '14',
    src: '/images/valentina/valentina-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  {
    id: '15',
    src: '/images/valentina/valentina-15.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валентина Антоненко',
    colored: false,
    slug: 'valentina-antonenko',
  },
  // Валентина Антоненко конец

  // Артем начало
  {
    id: '16',
    src: '/images/artem/artem-1.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '17',
    src: '/images/artem/artem-2.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '18',
    src: '/images/artem/artem-3.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '19',
    src: '/images/artem/artem-4.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '20',
    src: '/images/artem/artem-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '21',
    src: '/images/artem/artem-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '22',
    src: '/images/artem/artem-7.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: false,
    slug: 'sabo-artem',
  },
  {
    id: '23',
    src: '/images/artem/artem-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  {
    id: '24',
    src: '/images/artem/artem-9.webp',
    hairLength: 'По плечі',
    curlSize: 'Інтенсивний',
    master: 'Артем Сабо',
    colored: true,
    slug: 'sabo-artem',
  },
  // Артем конец

  // Кузьменко начало
  {
    id: '25',
    src: '/images/a-kuzmenko/kuzmenko-1.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '26',
    src: '/images/a-kuzmenko/kuzmenko-2.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '27',
    src: '/images/a-kuzmenko/kuzmenko-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: false,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '28',
    src: '/images/a-kuzmenko/kuzmenko-4.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '29',
    src: '/images/a-kuzmenko/kuzmenko-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '30',
    src: '/images/a-kuzmenko/kuzmenko-6.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '31',
    src: '/images/a-kuzmenko/kuzmenko-7.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '32',
    src: '/images/a-kuzmenko/kuzmenko-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '33',
    src: '/images/a-kuzmenko/kuzmenko-9.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '34',
    src: '/images/a-kuzmenko/kuzmenko-10.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '35',
    src: '/images/a-kuzmenko/kuzmenko-11.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  {
    id: '36',
    src: '/images/a-kuzmenko/kuzmenko-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Кузьменко',
    colored: true,
    slug: 'anastasia-kuzmenko',
  },
  // Кузьменко конец

  // vika omelchenko начало
  {
    id: '37',
    src: '/images/vika-omelchenko/vika-omelchenko-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '38',
    src: '/images/vika-omelchenko/vika-omelchenko-2.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '39',
    src: '/images/vika-omelchenko/vika-omelchenko-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '40',
    src: '/images/vika-omelchenko/vika-omelchenko-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '41',
    src: '/images/vika-omelchenko/vika-omelchenko-5.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '42',
    src: '/images/vika-omelchenko/vika-omelchenko-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '43',
    src: '/images/vika-omelchenko/vika-omelchenko-7.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '44',
    src: '/images/vika-omelchenko/vika-omelchenko-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '45',
    src: '/images/vika-omelchenko/vika-omelchenko-9.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '46',
    src: '/images/vika-omelchenko/vika-omelchenko-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '47',
    src: '/images/vika-omelchenko/vika-omelchenko-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '48',
    src: '/images/vika-omelchenko/vika-omelchenko-12.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: true,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '49',
    src: '/images/vika-omelchenko/vika-omelchenko-13.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '50',
    src: '/images/vika-omelchenko/vika-omelchenko-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '51',
    src: '/images/vika-omelchenko/vika-omelchenko-15.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  {
    id: '52',
    src: '/images/vika-omelchenko/vika-omelchenko-16.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Омельченко',
    colored: false,
    slug: 'viktoriya-omelchenko',
  },
  // vika omelchenko конец

  // Вікторія Салій начало
  {
    id: '53',
    src: '/images/viktoriya-salyi/viktoriya-salyi-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '54',
    src: '/images/viktoriya-salyi/viktoriya-salyi-2.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '55',
    src: '/images/viktoriya-salyi/viktoriya-salyi-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '56',
    src: '/images/viktoriya-salyi/viktoriya-salyi-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '57',
    src: '/images/viktoriya-salyi/viktoriya-salyi-5.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '58',
    src: '/images/viktoriya-salyi/viktoriya-salyi-6.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '59',
    src: '/images/viktoriya-salyi/viktoriya-salyi-7.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '60',
    src: '/images/viktoriya-salyi/viktoriya-salyi-8.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '61',
    src: '/images/viktoriya-salyi/viktoriya-salyi-9.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '62',
    src: '/images/viktoriya-salyi/viktoriya-salyi-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '63',
    src: '/images/viktoriya-salyi/viktoriya-salyi-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '64',
    src: '/images/viktoriya-salyi/viktoriya-salyi-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '65',
    src: '/images/viktoriya-salyi/viktoriya-salyi-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '66',
    src: '/images/viktoriya-salyi/viktoriya-salyi-14.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '67',
    src: '/images/viktoriya-salyi/viktoriya-salyi-15.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '68',
    src: '/images/viktoriya-salyi/viktoriya-salyi-16.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '69',
    src: '/images/viktoriya-salyi/viktoriya-salyi-17.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '70',
    src: '/images/viktoriya-salyi/viktoriya-salyi-18.webp',
    hairLength: 'Короткі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: true,
    slug: 'viktoriya-salyi',
  },
  {
    id: '71',
    src: '/images/viktoriya-salyi/viktoriya-salyi-19.webp',
    hairLength: 'Короткі',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '72',
    src: '/images/viktoriya-salyi/viktoriya-salyi-20.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '73',
    src: '/images/viktoriya-salyi/viktoriya-salyi-21.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  {
    id: '74',
    src: '/images/viktoriya-salyi/viktoriya-salyi-22.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Вікторія Салій',
    colored: false,
    slug: 'viktoriya-salyi',
  },
  // Вікторія Салій конец

  // Юлия Броварчук начало
  {
    id: '75',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-1.webp',
    hairLength: 'По лопатки',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '76',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-2.webp',
    hairLength: 'По лопатки',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '77',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '78',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '79',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '80',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-6.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '81',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-7.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '82',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-8.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '83',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-9.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '84',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-10.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '85',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-11.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '86',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-12.webp',
    hairLength: 'По лопатки',
    curlSize: 'Великий',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '87',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: false,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '88',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '89',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-15.webp',
    hairLength: 'По плечі',
    curlSize: 'Карвінг',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  {
    id: '90',
    src: '/images/yulia-brovarkchuk/yulia-brovarkchuk-16.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Юлія Броварчук',
    colored: true,
    slug: 'yulia-brovarkchuk',
  },
  // Юлия Броварчук конец

  // Валерія Мельниченко начало
  {
    id: '91',
    src: '/images/valeria-melnichenko/valeria-melnichenko-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валерія Мельниченко',
    colored: false,
    slug: 'valeria-melnichenko',
  },
  {
    id: '92',
    src: '/images/valeria-melnichenko/valeria-melnichenko-2.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Валерія Мельниченко',
    colored: false,
    slug: 'valeria-melnichenko',
  },
  {
    id: '93',
    src: '/images/valeria-melnichenko/valeria-melnichenko-3.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Валерія Мельниченко',
    colored: true,
    slug: 'valeria-melnichenko',
  },
  {
    id: '94',
    src: '/images/valeria-melnichenko/valeria-melnichenko-4.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валерія Мельниченко',
    colored: false,
    slug: 'valeria-melnichenko',
  },
  {
    id: '95',
    src: '/images/valeria-melnichenko/valeria-melnichenko-5.webp',
    hairLength: 'По лопатки',
    curlSize: 'Великий',
    master: 'Валерія Мельниченко',
    colored: true,
    slug: 'valeria-melnichenko',
  },
  {
    id: '96',
    src: '/images/valeria-melnichenko/valeria-melnichenko-6.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Валерія Мельниченко',
    colored: true,
    slug: 'valeria-melnichenko',
  },
  {
    id: '97',
    src: '/images/valeria-melnichenko/valeria-melnichenko-7.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Валерія Мельниченко',
    colored: false,
    slug: 'valeria-melnichenko',
  },
  {
    id: '98',
    src: '/images/valeria-melnichenko/valeria-melnichenko-8.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Валерія Мельниченко',
    colored: true,
    slug: 'valeria-melnichenko',
  },
  {
    id: '99',
    src: '/images/valeria-melnichenko/valeria-melnichenko-9.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Валерія Мельниченко',
    colored: false,
    slug: 'valeria-melnichenko',
  },
  // Валерія Мельниченко конец

  // Анастасия Мальчик начало
  {
    id: '100',
    src: '/images/anastasiya-malchik/anastasiya-malchik-1.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '101',
    src: '/images/anastasiya-malchik/anastasiya-malchik-2.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: true,
    slug: 'anastasiya-malchik',
  },
  {
    id: '102',
    src: '/images/anastasiya-malchik/anastasiya-malchik-3.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '103',
    src: '/images/anastasiya-malchik/anastasiya-malchik-4.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: true,
    slug: 'anastasiya-malchik',
  },
  {
    id: '104',
    src: '/images/anastasiya-malchik/anastasiya-malchik-5.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '105',
    src: '/images/anastasiya-malchik/anastasiya-malchik-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Великий',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '106',
    src: '/images/anastasiya-malchik/anastasiya-malchik-7.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '107',
    src: '/images/anastasiya-malchik/anastasiya-malchik-8.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '108',
    src: '/images/anastasiya-malchik/anastasiya-malchik-9.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '109',
    src: '/images/anastasiya-malchik/anastasiya-malchik-10.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '110',
    src: '/images/anastasiya-malchik/anastasiya-malchik-11.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '111',
    src: '/images/anastasiya-malchik/anastasiya-malchik-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  {
    id: '112',
    src: '/images/anastasiya-malchik/anastasiya-malchik-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Анастасія Мальчик',
    colored: false,
    slug: 'anastasiya-malchik',
  },
  // Анастасия Мальчик конец

  // Діана Лєканцева начало
  {
    id: '113',
    src: '/images/diana-lekanceva/diana-lekanceva-1.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  {
    id: '114',
    src: '/images/diana-lekanceva/diana-lekanceva-2.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  {
    id: '115',
    src: '/images/diana-lekanceva/diana-lekanceva-3.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  {
    id: '116',
    src: '/images/diana-lekanceva/diana-lekanceva-4.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  {
    id: '117',
    src: '/images/diana-lekanceva/diana-lekanceva-5.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  {
    id: '118',
    src: '/images/diana-lekanceva/diana-lekanceva-6.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Діана Лєканцева',
    colored: true,
    slug: 'diana-lekanceva',
  },
  {
    id: '119',
    src: '/images/diana-lekanceva/diana-lekanceva-7.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Діана Лєканцева',
    colored: true,
    slug: 'diana-lekanceva',
  },
  {
    id: '120',
    src: '/images/diana-lekanceva/diana-lekanceva-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Діана Лєканцева',
    colored: false,
    slug: 'diana-lekanceva',
  },
  // Діана Лєканцева конец

  // Ольга Колле начало
  {
    id: '121',
    src: '/images/olga-kolle/olga-kolle-1.webp',
    hairLength: 'По лопатки',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '122',
    src: '/images/olga-kolle/olga-kolle-2.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '123',
    src: '/images/olga-kolle/olga-kolle-3.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '124',
    src: '/images/olga-kolle/olga-kolle-4.webp',
    hairLength: 'За лопатки',
    curlSize: 'Карвінг',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '125',
    src: '/images/olga-kolle/olga-kolle-5.webp',
    hairLength: 'По лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '126',
    src: '/images/olga-kolle/olga-kolle-6.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '127',
    src: '/images/olga-kolle/olga-kolle-7.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '128',
    src: '/images/olga-kolle/olga-kolle-8.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '129',
    src: '/images/olga-kolle/olga-kolle-9.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '130',
    src: '/images/olga-kolle/olga-kolle-10.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '131',
    src: '/images/olga-kolle/olga-kolle-11.webp',
    hairLength: 'По лопатки',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '132',
    src: '/images/olga-kolle/olga-kolle-12.webp',
    hairLength: 'По пояс',
    curlSize: 'Інтенсивний',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '133',
    src: '/images/olga-kolle/olga-kolle-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Пляжна Хвиля',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '134',
    src: '/images/olga-kolle/olga-kolle-14.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '135',
    src: '/images/olga-kolle/olga-kolle-15.webp',
    hairLength: 'По плечі',
    curlSize: 'Інтенсивний',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '136',
    src: '/images/olga-kolle/olga-kolle-16.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '137',
    src: '/images/olga-kolle/olga-kolle-17.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '138',
    src: '/images/olga-kolle/olga-kolle-18.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '139',
    src: '/images/olga-kolle/olga-kolle-19.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: true,
    slug: 'olga-kolle',
  },
  {
    id: '140',
    src: '/images/olga-kolle/olga-kolle-20.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '141',
    src: '/images/olga-kolle/olga-kolle-21.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  {
    id: '142',
    src: '/images/olga-kolle/olga-kolle-22.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Ольга Колле',
    colored: false,
    slug: 'olga-kolle',
  },
  // Ольга Колле конец

  // Ярослава Гурбік начало
  {
    id: '143',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-1.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '144',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-2.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '145',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-3.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '146',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-4.webp',
    hairLength: 'По пояс',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '147',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-5.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '148',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-6.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '149',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-7.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '150',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-8.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '151',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-9.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '152',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-10.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '153',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-11.webp',
    hairLength: 'По пояс',
    curlSize: 'Інтенсивний',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '154',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-12.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '155',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-13.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '156',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-14.webp',
    hairLength: 'По плечі',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '157',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-15.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '158',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-16.webp',
    hairLength: 'По лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '159',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-17.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '160',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-18.webp',
    hairLength: 'За лопатки',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '161',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-19.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '162',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-20.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '163',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-21.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '164',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-22.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '165',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-23.webp',
    hairLength: 'Короткі',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '166',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-24.webp',
    hairLength: 'По плечі',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: true,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '167',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-25.webp',
    hairLength: 'За лопатки',
    curlSize: 'Інтенсивний',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '168',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-26.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '169',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-27.webp',
    hairLength: 'За лопатки',
    curlSize: 'Середній',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  {
    id: '170',
    src: '/images/yaroslava-gurbik/yaroslava-gurbik-28.webp',
    hairLength: 'По пояс',
    curlSize: 'Великий',
    master: 'Ярослава Гурбік',
    colored: false,
    slug: 'yaroslava-gurbik',
  },
  // Ярослава Гурбік конец
];
